
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GREATERTHAN = 25;
  public static final int STRLIT = 8;
  public static final int DIVIDE = 21;
  public static final int INCREMENT = 34;
  public static final int MULT = 20;
  public static final int CHAR = 3;
  public static final int SUBTRACT = 23;
  public static final int BACKSLASH = 30;
  public static final int INT = 2;
  public static final int DECREMENT = 35;
  public static final int TILDE = 45;
  public static final int SEMICOLON = 46;
  public static final int AND = 32;
  public static final int INTLIT = 49;
  public static final int LESSTHAN = 24;
  public static final int OR = 31;
  public static final int COMMA = 43;
  public static final int BOOL = 4;
  public static final int CLASS = 14;
  public static final int FI = 51;
  public static final int IF = 16;
  public static final int ID = 48;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int PRINTLINE = 13;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int ADD = 22;
  public static final int OPENPARAN = 36;
  public static final int VOID = 19;
  public static final int EQ = 28;
  public static final int FLOATLIT = 6;
  public static final int ASSMNT = 33;
  public static final int OPENCURLY = 40;
  public static final int CHARLIT = 7;
  public static final int COLON = 42;
  public static final int ELSE = 15;
  public static final int CLOSEDPARAN = 37;
  public static final int READ = 11;
  public static final int FINAL = 50;
  public static final int QUEST = 44;
  public static final int WHILE = 17;
  public static final int OPENBRACK = 38;
  public static final int CLOSEDCURLY = 41;
  public static final int LESSTHANEQ = 26;
  public static final int FLOAT = 5;
  public static final int CLOSEDBRACK = 39;
  public static final int GREATERTHANEQ = 27;
  public static final int FALSE = 10;
  public static final int VAR = 47;
  public static final int PRINT = 12;
  public static final int NOTEQ = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "CHAR",
  "BOOL",
  "FLOAT",
  "FLOATLIT",
  "CHARLIT",
  "STRLIT",
  "TRUE",
  "FALSE",
  "READ",
  "PRINT",
  "PRINTLINE",
  "CLASS",
  "ELSE",
  "IF",
  "WHILE",
  "RETURN",
  "VOID",
  "MULT",
  "DIVIDE",
  "ADD",
  "SUBTRACT",
  "LESSTHAN",
  "GREATERTHAN",
  "LESSTHANEQ",
  "GREATERTHANEQ",
  "EQ",
  "NOTEQ",
  "BACKSLASH",
  "OR",
  "AND",
  "ASSMNT",
  "INCREMENT",
  "DECREMENT",
  "OPENPARAN",
  "CLOSEDPARAN",
  "OPENBRACK",
  "CLOSEDBRACK",
  "OPENCURLY",
  "CLOSEDCURLY",
  "COLON",
  "COMMA",
  "QUEST",
  "TILDE",
  "SEMICOLON",
  "VAR",
  "ID",
  "INTLIT",
  "FINAL",
  "FI"
  };
}

